export const ADD_NEW_FILAMENT = '@@FILAMENTS/ADD_NEW_FILAMENT';
export const ADD_NEW_FILAMENT_FULFILLED = '@@FILAMENTS/ADD_NEW_FILAMENT_FULFILLED';
export const SELECT_FILAMENT = '@@FILAMENTS/SELECT_FILAMENT';
export const DELETE_FILAMENT = '@@FILAMENTS/DELETE_FILAMENT';
