export const ADD_NEW_PRINTER = '@@PRINTERS/ADD_NEW_PRINTER';
export const ADD_NEW_PRINTER_FULFILLED = '@@PRINTERS/ADD_NEW_PRINTER_FULFILLED';
export const SELECT_PRINTER = '@@PRINTERS/SELECT_PRINTER';
export const DELETE_PRINTER = '@@PRINTERS/DELETE_PRINTER';
